language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

install:
  - export PATH=${PATH}:${HOME}/gopath/bin
  - go get -v golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

before_script:
  - go vet ./...
  - golint .

script:
  - go test -v ./...
  - go test -v -test.race ./...
  - goveralls -service=travis-ci
